/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tp5;

/**
 *
 * @author Luly2
 */
public class BusqClienteDirectorioPorCiudad extends javax.swing.JInternalFrame {

    /**
     * Creates new form BusqClienteDirectorioPorCiudad
     */
    public BusqClienteDirectorioPorCiudad() {
        initComponents();
        cargarComboCiudades();
    }
    
    private void cargarComboCiudades(){
        jCboxCiudades.removeAllItems();
        for(String c : Menu.ciudades){
            jCboxCiudades.addItem(c);
        }
        jCboxCiudades.setSelectedItem(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbuscarCliente = new javax.swing.JLabel();
        jlCiudades = new javax.swing.JLabel();
        jCboxCiudades = new javax.swing.JComboBox<>();
        jBsalir = new javax.swing.JButton();
        jTablaCiudad = new javax.swing.JScrollPane();
        jTdatos = new javax.swing.JTable();

        jLbuscarCliente.setFont(new java.awt.Font("MingLiU-ExtB", 1, 24)); // NOI18N
        jLbuscarCliente.setText("Buscar Clientes de Directorio por Ciudad");

        jlCiudades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlCiudades.setText("Ciudades:");

        jCboxCiudades.addItemListener(this::jCboxCiudadesItemStateChanged);

        jBsalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBsalir.setText("Salir");
        jBsalir.addActionListener(this::jBsalirActionPerformed);

        jTdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Direccion", "Ciudad", "Telefono"
            }
        ));
        jTablaCiudad.setViewportView(jTdatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLbuscarCliente)
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCiudades)
                                    .addComponent(jCboxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTablaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLbuscarCliente)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCiudades)
                        .addGap(18, 18, 18)
                        .addComponent(jCboxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTablaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboxCiudadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboxCiudadesItemStateChanged
        // TODO add your handling code here:
        if(jCboxCiudades.getSelectedItem() == null) return;
            
        String ciudad = jCboxCiudades.getSelectedItem().toString();
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTdatos.getModel();
        modelo.setRowCount(0);
        
        for(Contacto c : Menu.directorio.buscarContactos(ciudad)){
            Long telef = null;
            for(Long t : Menu.directorio.getTelefonos()){
                if(Menu.directorio.buscarContacto(t).equals(c)){
                    telef = t;
                    break;
                }
            }
            modelo.addRow(new Object[]{c.getDni(), c.getApellido(), c.getNombre(), c.getDireccion(), c.getCiudad()});
        }
    }//GEN-LAST:event_jCboxCiudadesItemStateChanged

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jBsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<String> jCboxCiudades;
    private javax.swing.JLabel jLbuscarCliente;
    private javax.swing.JScrollPane jTablaCiudad;
    private javax.swing.JTable jTdatos;
    private javax.swing.JLabel jlCiudades;
    // End of variables declaration//GEN-END:variables
}
