/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tp5;

import javax.swing.DefaultListModel;

/**
 *
 * @author Luly2
 */
public class BusquedaDeClientes extends javax.swing.JInternalFrame {

    
    private Directorio directorio;
    
    public BusquedaDeClientes(Directorio directorio) {
        initComponents();
        this.directorio = directorio;
        llenarListaTelefonos();
    }
    private void llenarListaTelefonos(){
        DefaultListModel<Long>  modelo = new DefaultListModel();
        
        for(Long telefono : directorio.getTelefonos()){
            modelo.addElement(telefono);
        }

        jListTelefonos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitulo = new javax.swing.JLabel();
        jLtelefono = new javax.swing.JLabel();
        jTFtelef = new javax.swing.JTextField();
        jLdni = new javax.swing.JLabel();
        jLapellido = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jLciudad = new javax.swing.JLabel();
        jLdomicilio = new javax.swing.JLabel();
        jBsalir = new javax.swing.JButton();
        jTFdni = new javax.swing.JTextField();
        jTFapellido = new javax.swing.JTextField();
        jTFnombre = new javax.swing.JTextField();
        jTFciudad = new javax.swing.JTextField();
        jTFdomicilio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTelefonos = new javax.swing.JList<>();

        jLtitulo.setFont(new java.awt.Font("MingLiU-ExtB", 1, 18)); // NOI18N
        jLtitulo.setText("Busqueda de Clientes");

        jLtelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLtelefono.setText("Telefono:");

        jLdni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLdni.setText("DNI:");

        jLapellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLapellido.setText("Apellido:");

        jLnombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLnombre.setText("Nombre:");

        jLciudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLciudad.setText("Ciudad:");

        jLdomicilio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLdomicilio.setText("Domicilio:");

        jBsalir.setText("Salir");
        jBsalir.addActionListener(this::jBsalirActionPerformed);

        jTFdni.addActionListener(this::jTFdniActionPerformed);

        jTFapellido.addActionListener(this::jTFapellidoActionPerformed);

        jTFciudad.addActionListener(this::jTFciudadActionPerformed);

        jListTelefonos.addListSelectionListener(this::jListTelefonosValueChanged);
        jScrollPane1.setViewportView(jListTelefonos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBsalir)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLtelefono)
                                .addGap(18, 18, 18)
                                .addComponent(jTFtelef, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLdomicilio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFdomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLciudad)
                                .addGap(26, 26, 26)
                                .addComponent(jTFciudad))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLnombre)
                                    .addComponent(jLdni)
                                    .addComponent(jLapellido))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFdni)
                                    .addComponent(jTFapellido)
                                    .addComponent(jTFnombre))))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLtitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLtelefono)
                            .addComponent(jTFtelef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLapellido)
                                    .addComponent(jTFdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLnombre)
                                    .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLciudad)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLdni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLdomicilio))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jBsalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdniActionPerformed

    private void jTFapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFapellidoActionPerformed

    private void jTFciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFciudadActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jListTelefonosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTelefonosValueChanged
       if(!evt.getValueIsAdjusting()){
           Long telefono = jListTelefonos.getSelectedValue();
           if(telefono != null){
               Contacto contacto = directorio.buscarContacto(telefono);
               
               long dni = contacto.getDni();
               jTFdni.setText(String.valueOf(dni));
               jTFapellido.setText(contacto.getApellido());
               jTFnombre.setText(contacto.getNombre());
               jTFciudad.setText(contacto.getCiudad());
               jTFdomicilio.setText(contacto.getDireccion());
           }
       
    }
    }//GEN-LAST:event_jListTelefonosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLapellido;
    private javax.swing.JLabel jLciudad;
    private javax.swing.JLabel jLdni;
    private javax.swing.JLabel jLdomicilio;
    private javax.swing.JList<Long> jListTelefonos;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JLabel jLtelefono;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFapellido;
    private javax.swing.JTextField jTFciudad;
    private javax.swing.JTextField jTFdni;
    private javax.swing.JTextField jTFdomicilio;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JTextField jTFtelef;
    // End of variables declaration//GEN-END:variables
}
