/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tp5;

import javax.swing.DefaultListModel;

/**
 *
 * @author Luly2
 */
public class BusquedaDeClientes extends javax.swing.JInternalFrame {

    
    private Directorio directorio;
    
    public BusquedaDeClientes(Directorio directorio) {
        initComponents();
        this.directorio = directorio;
        llenarListaTelefonos();
    }
    private void llenarListaTelefonos(){
        DefaultListModel<Long>  modelo = new DefaultListModel();
        
        for(Long telefono : directorio.getTelefonos()){
            modelo.addElement(telefono);
        }

        jListTelefonos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitulo = new javax.swing.JLabel();
        jLtelefono = new javax.swing.JLabel();
        jTFtelef = new javax.swing.JTextField();
        jLdni = new javax.swing.JLabel();
        jLapellido = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jLciudad = new javax.swing.JLabel();
        jLdomicilio = new javax.swing.JLabel();
        jBsalir = new javax.swing.JButton();
        jTFapellidoo = new javax.swing.JTextField();
        jTFdni = new javax.swing.JTextField();
        jTFnombre = new javax.swing.JTextField();
        jTFciudad = new javax.swing.JTextField();
        jTFdomicilio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTelefonos = new javax.swing.JList<>();

        jLtitulo.setFont(new java.awt.Font("MingLiU-ExtB", 1, 24)); // NOI18N
        jLtitulo.setText("Busqueda de Clientes");

        jLtelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLtelefono.setText("Telefono:");

        jLdni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLdni.setText("DNI:");

        jLapellido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLapellido.setText("Apellido:");

        jLnombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLnombre.setText("Nombre:");

        jLciudad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLciudad.setText("Ciudad:");

        jLdomicilio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLdomicilio.setText("Domicilio:");

        jBsalir.setText("Salir");
        jBsalir.addActionListener(this::jBsalirActionPerformed);

        jTFapellidoo.addActionListener(this::jTFapellidooActionPerformed);

        jTFdni.addActionListener(this::jTFdniActionPerformed);

        jTFciudad.addActionListener(this::jTFciudadActionPerformed);

        jListTelefonos.addListSelectionListener(this::jListTelefonosValueChanged);
        jScrollPane1.setViewportView(jListTelefonos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFtelef, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLdni)
                                        .addComponent(jLapellido))
                                    .addComponent(jLnombre))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLciudad)
                                    .addComponent(jLdomicilio))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFdomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(jTFciudad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFapellidoo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFdni, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFnombre))
                                .addGap(19, 19, 19))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jTFtelef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLdni)
                            .addComponent(jTFdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLapellido)
                            .addComponent(jTFapellidoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLnombre)
                            .addComponent(jTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLciudad)
                            .addComponent(jTFciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLdomicilio)
                            .addComponent(jTFdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFapellidooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFapellidooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFapellidooActionPerformed

    private void jTFdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdniActionPerformed

    private void jTFciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFciudadActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jListTelefonosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTelefonosValueChanged
       if(!evt.getValueIsAdjusting()){
           Long telefono = jListTelefonos.getSelectedValue();
           if(telefono != null){
               Contacto contacto = directorio.buscarContacto(telefono);
               
               long dni = contacto.getDni();
               jTFapellidoo.setText(contacto.getApellido());
               jTFdni.setText(String.valueOf(dni));
               jTFnombre.setText(contacto.getNombre());
               jTFciudad.setText(contacto.getCiudad());
               jTFdomicilio.setText(contacto.getDireccion());
           }
       
    }
    }//GEN-LAST:event_jListTelefonosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLapellido;
    private javax.swing.JLabel jLciudad;
    private javax.swing.JLabel jLdni;
    private javax.swing.JLabel jLdomicilio;
    private javax.swing.JList<Long> jListTelefonos;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JLabel jLtelefono;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFapellidoo;
    private javax.swing.JTextField jTFciudad;
    private javax.swing.JTextField jTFdni;
    private javax.swing.JTextField jTFdomicilio;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JTextField jTFtelef;
    // End of variables declaration//GEN-END:variables
}
