/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp5;

import java.awt.Color;

/**
 *
 * @author Luly2
 */
public class Menu extends javax.swing.JFrame {
    
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    public static Directorio directorio = new Directorio();
    public static java.util.TreeSet<String> ciudades = new java.util.TreeSet<>();
    
    public Menu() {
        initComponents();
        this.getContentPane().setBackground(new Color(51, 102, 153));
        ciudades.add("San Luis");
        ciudades.add("Merlo");
        ciudades.add("Villa Mercedes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMcliente = new javax.swing.JMenu();
        jItAgCliente = new javax.swing.JMenuItem();
        jItbusCliente = new javax.swing.JMenuItem();
        jItborrarCliente = new javax.swing.JMenuItem();
        jMdirectorio = new javax.swing.JMenu();
        jItbusClientporCiudad = new javax.swing.JMenuItem();
        jItbusTelporApellido = new javax.swing.JMenuItem();
        jMciudades = new javax.swing.JMenu();
        jItagregarCiudad = new javax.swing.JMenuItem();
        jMsalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        setPreferredSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMcliente.setText("Clientes");

        jItAgCliente.setText("Agregar cliente");
        jItAgCliente.addActionListener(this::jItAgClienteActionPerformed);
        jMcliente.add(jItAgCliente);

        jItbusCliente.setText("Buscar Cliente");
        jItbusCliente.addActionListener(this::jItbusClienteActionPerformed);
        jMcliente.add(jItbusCliente);

        jItborrarCliente.setText("Borrar Cliente");
        jItborrarCliente.addActionListener(this::jItborrarClienteActionPerformed);
        jMcliente.add(jItborrarCliente);

        jMenuBar1.add(jMcliente);

        jMdirectorio.setText("Directorio");

        jItbusClientporCiudad.setText("Buscar Clientes por Ciudad");
        jItbusClientporCiudad.addActionListener(this::jItbusClientporCiudadActionPerformed);
        jMdirectorio.add(jItbusClientporCiudad);

        jItbusTelporApellido.setText("Buscar Telefono por Apellido");
        jItbusTelporApellido.addActionListener(this::jItbusTelporApellidoActionPerformed);
        jMdirectorio.add(jItbusTelporApellido);

        jMenuBar1.add(jMdirectorio);

        jMciudades.setText("Ciudades");

        jItagregarCiudad.setText("Agregar Ciudad");
        jItagregarCiudad.addActionListener(this::jItagregarCiudadActionPerformed);
        jMciudades.add(jItagregarCiudad);

        jMenuBar1.add(jMciudades);

        jMsalir.setText("Salir");
        jMenuBar1.add(jMsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItborrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItborrarClienteActionPerformed
     escritorio.removeAll();
        BorrarCliente bc = new BorrarCliente();
        escritorio.add(bc);
        bc.setVisible(true);
        escritorio.moveToFront(bc);
        escritorio.revalidate();
        escritorio.repaint();
    }//GEN-LAST:event_jItborrarClienteActionPerformed

    private void jItAgClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItAgClienteActionPerformed
        escritorio.removeAll();
        AgregarCliente ac = new AgregarCliente(directorio);
        escritorio.add(ac);
        ac.setVisible(true);
        escritorio.moveToFront(ac);
        escritorio.revalidate();
        escritorio.repaint();
                
    }//GEN-LAST:event_jItAgClienteActionPerformed

    private void jItbusClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItbusClienteActionPerformed
         escritorio.removeAll();
        BusquedaDeClientes bdc = new BusquedaDeClientes(directorio);
        escritorio.add(bdc);
        bdc.setVisible(true);
        escritorio.moveToFront(bdc);
        escritorio.revalidate();
        escritorio.repaint();
                
    }//GEN-LAST:event_jItbusClienteActionPerformed

    private void jItbusClientporCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItbusClientporCiudadActionPerformed
        escritorio.removeAll();
        BusqClienteDirectorioPorCiudad bcdc = new BusqClienteDirectorioPorCiudad();
        escritorio.add(bcdc);
        bcdc.setVisible(true);
        escritorio.moveToFront(bcdc);
        escritorio.revalidate();
        escritorio.repaint();
        
                
    }//GEN-LAST:event_jItbusClientporCiudadActionPerformed

    private void jItagregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItagregarCiudadActionPerformed
        escritorio.removeAll();
        AgregarCiudad agC = new AgregarCiudad();
        escritorio.add(agC);
        agC.setVisible(true);
        escritorio.moveToFront(agC);
        escritorio.revalidate();
        escritorio.repaint();
        
    }//GEN-LAST:event_jItagregarCiudadActionPerformed

    private void jItbusTelporApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItbusTelporApellidoActionPerformed
        escritorio.removeAll();
        BuscarTelefonoPorApellido bta = new BuscarTelefonoPorApellido();
        escritorio.add(bta);
        bta.setVisible(true);
        escritorio.moveToFront(bta);
        escritorio.revalidate();
        escritorio.repaint();
        
    }//GEN-LAST:event_jItbusTelporApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jItAgCliente;
    private javax.swing.JMenuItem jItagregarCiudad;
    private javax.swing.JMenuItem jItborrarCliente;
    private javax.swing.JMenuItem jItbusCliente;
    private javax.swing.JMenuItem jItbusClientporCiudad;
    private javax.swing.JMenuItem jItbusTelporApellido;
    private javax.swing.JMenu jMciudades;
    private javax.swing.JMenu jMcliente;
    private javax.swing.JMenu jMdirectorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMsalir;
    // End of variables declaration//GEN-END:variables
}
